version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Nicosia'
    allow:
      - dependency-type: 'all'
    groups:
      all-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/packages/admin-ui'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Nicosia'
    allow:
      - dependency-type: 'all'
    groups:
      all-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/packages/create-admin-ui'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Nicosia'
    allow:
      - dependency-type: 'all'
    groups:
      all-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/packages/demo'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Nicosia'
    allow:
      - dependency-type: 'all'
    groups:
      all-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'deps'
      include: 'scope'
